import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard Amazon",
  description: "Generated by Dashboard Amazon",
};


export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
 
  return (
    <html lang="en">
      <body>
        {/* Layout UI */}
        {/* Place children where you want to render a page or nested layout */}
        <main className="text-red-500">{children}</main>
      </body>
    </html>
  )
}